# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Stopwatch(object):
    def setupUi(self, Stopwatch):
        Stopwatch.setObjectName("Stopwatch")
        Stopwatch.resize(370, 449)
        Stopwatch.setMinimumSize(QtCore.QSize(370, 449))
        Stopwatch.setMaximumSize(QtCore.QSize(370, 449))
        self.centralwidget = QtWidgets.QWidget(parent=Stopwatch)
        self.centralwidget.setObjectName("centralwidget")
        self.time_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(10, 50, 341, 111))
        font = QtGui.QFont()
        font.setFamily("PT Mono")
        font.setPointSize(50)
        self.time_label.setFont(font)
        self.time_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.start_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(20, 170, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.start_button.setFont(font)
        self.start_button.setObjectName("start_button")
        self.reset_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(200, 170, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.reset_button.setFont(font)
        self.reset_button.setObjectName("reset_button")
        self.quit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.quit_button.setGeometry(QtCore.QRect(270, 10, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.quit_button.setFont(font)
        self.quit_button.setObjectName("quit_button")
        self.laps_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.laps_label.setGeometry(QtCore.QRect(20, 320, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.laps_label.setFont(font)
        self.laps_label.setObjectName("laps_label")
        self.lap1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lap1.setGeometry(QtCore.QRect(20, 360, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lap1.setFont(font)
        self.lap1.setText("")
        self.lap1.setObjectName("lap1")
        self.lap_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.lap_button.setGeometry(QtCore.QRect(110, 240, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lap_button.setFont(font)
        self.lap_button.setObjectName("lap_button")
        Stopwatch.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Stopwatch)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 22))
        self.menubar.setObjectName("menubar")
        self.menuStopwatch = QtWidgets.QMenu(parent=self.menubar)
        self.menuStopwatch.setObjectName("menuStopwatch")
        Stopwatch.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Stopwatch)
        self.statusbar.setObjectName("statusbar")
        Stopwatch.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuStopwatch.menuAction())

        self.retranslateUi(Stopwatch)
        QtCore.QMetaObject.connectSlotsByName(Stopwatch)

    def retranslateUi(self, Stopwatch):
        _translate = QtCore.QCoreApplication.translate
        Stopwatch.setWindowTitle(_translate("Stopwatch", "Stopwatch"))
        self.time_label.setText(_translate("Stopwatch", "00:00:00.00"))
        self.start_button.setText(_translate("Stopwatch", "Start"))
        self.reset_button.setText(_translate("Stopwatch", "Reset"))
        self.quit_button.setText(_translate("Stopwatch", "Quit"))
        self.laps_label.setText(_translate("Stopwatch", "Current Lap:"))
        self.lap_button.setText(_translate("Stopwatch", "Lap"))
        self.menuStopwatch.setTitle(_translate("Stopwatch", "Stopwatch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Stopwatch = QtWidgets.QMainWindow()
    ui = Ui_Stopwatch()
    ui.setupUi(Stopwatch)
    Stopwatch.show()
    sys.exit(app.exec())
